version: '3.8'

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: staydesk-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./staydesk.db
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_RELOAD=true
      - HOTEL_NAME=Staydesk Resort
      - HOTEL_LOCATION=Miami Beach, FL
      - NLP_SERVICE_URL=http://nlp-service:8001
      - SECRET_KEY=dev-secret-key-change-in-production
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8001,http://localhost:8025
      - LOG_LEVEL=INFO
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    networks:
      - staydesk-network
    restart: unless-stopped

networks:
  staydesk-network:
    external: true 